"""add change log table

Revision ID: 1f18ca2228cf
Revises: 888921fe3a28
Create Date: 2026-09-25 04:58:29.135173

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f18ca2228cf'
down_revision: Union[str, Sequence[str], None] = '888921fe3a28'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('change_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('competitor_id', sa.Integer(), nullable=False),
    sa.Column('change_type', sa.String(length=30), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('detected_at', sa.DateTime(), nullable=False),
    sa.Column('is_read', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['competitor_id'], ['competitors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_change_log_company_id'), 'change_log', ['company_id'], unique=False)
    op.create_index(op.f('ix_change_log_competitor_id'), 'change_log', ['competitor_id'], unique=False)
    op.create_index(op.f('ix_change_log_id'), 'change_log', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_change_log_id'), table_name='change_log')
    op.drop_index(op.f('ix_change_log_competitor_id'), table_name='change_log')
    op.drop_index(op.f('ix_change_log_company_id'), table_name='change_log')
    op.drop_table('change_log')
    # ### end Alembic commands ###
