"""check for changes

Revision ID: 32723ad41902
Revises: 4987efaf2b2f
Create Date: 2026-10-03 03:26:46.313413

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '32723ad41902'
down_revision: Union[str, Sequence[str], None] = '4987efaf2b2f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'verification_code')
    op.drop_column('users', 'verification_code_expires_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('verification_code_expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('verification_code', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
