"""add competitor insights table

Revision ID: 888921fe3a28
Revises: bb0913910e30
Create Date: 2026-09-24 05:28:07.744208

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '888921fe3a28'
down_revision: Union[str, Sequence[str], None] = 'bb0913910e30'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('competitor_insights',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('competitor_id', sa.Integer(), nullable=False),
    sa.Column('tagline', sa.String(length=300), nullable=True),
    sa.Column('target_market', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('strengths', sa.Text(), nullable=True),
    sa.Column('weaknesses', sa.Text(), nullable=True),
    sa.Column('opportunities', sa.Text(), nullable=True),
    sa.Column('threats', sa.Text(), nullable=True),
    sa.Column('recent_signals', sa.Text(), nullable=True),
    sa.Column('sources', sa.Text(), nullable=True),
    sa.Column('researched_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['competitor_id'], ['competitors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_competitor_insights_company_id'), 'competitor_insights', ['company_id'], unique=False)
    op.create_index(op.f('ix_competitor_insights_competitor_id'), 'competitor_insights', ['competitor_id'], unique=True)
    op.create_index(op.f('ix_competitor_insights_id'), 'competitor_insights', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_competitor_insights_id'), table_name='competitor_insights')
    op.drop_index(op.f('ix_competitor_insights_competitor_id'), table_name='competitor_insights')
    op.drop_index(op.f('ix_competitor_insights_company_id'), table_name='competitor_insights')
    op.drop_table('competitor_insights')
    # ### end Alembic commands ###
