"""add research usage tracking

Revision ID: b8a5c44eabc5
Revises: 80b0d70f9328
Create Date: 2026-10-02 05:27:52.484071

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8a5c44eabc5'
down_revision: Union[str, Sequence[str], None] = '80b0d70f9328'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('research_usage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('competitor_name', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_research_usage_company_id'), 'research_usage', ['company_id'], unique=False)
    op.create_index(op.f('ix_research_usage_id'), 'research_usage', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_research_usage_id'), table_name='research_usage')
    op.drop_index(op.f('ix_research_usage_company_id'), table_name='research_usage')
    op.drop_table('research_usage')
    # ### end Alembic commands ###
