"""add research history table

Revision ID: f39b8a81fa9c
Revises: ab87d3d99204
Create Date: 2026-10-03 04:22:40.186081

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f39b8a81fa9c'
down_revision: Union[str, Sequence[str], None] = 'ab87d3d99204'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('research_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('competitor_id', sa.Integer(), nullable=True),
    sa.Column('competitor_name', sa.String(length=200), nullable=False),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('result', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['competitor_id'], ['competitors.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_research_history_company_created', 'research_history', ['company_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_research_history_company_id'), 'research_history', ['company_id'], unique=False)
    op.create_index(op.f('ix_research_history_competitor_id'), 'research_history', ['competitor_id'], unique=False)
    op.create_index(op.f('ix_research_history_competitor_name'), 'research_history', ['competitor_name'], unique=False)
    op.create_index(op.f('ix_research_history_created_at'), 'research_history', ['created_at'], unique=False)
    op.create_index(op.f('ix_research_history_id'), 'research_history', ['id'], unique=False)
    op.create_index(op.f('ix_research_history_user_id'), 'research_history', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_research_history_user_id'), table_name='research_history')
    op.drop_index(op.f('ix_research_history_id'), table_name='research_history')
    op.drop_index(op.f('ix_research_history_created_at'), table_name='research_history')
    op.drop_index(op.f('ix_research_history_competitor_name'), table_name='research_history')
    op.drop_index(op.f('ix_research_history_competitor_id'), table_name='research_history')
    op.drop_index(op.f('ix_research_history_company_id'), table_name='research_history')
    op.drop_index('ix_research_history_company_created', table_name='research_history')
    op.drop_table('research_history')
    # ### end Alembic commands ###
